apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init
  namespace: retailpulse
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: airflow-init
    spec:
      restartPolicy: OnFailure
      containers:
        - name: airflow-init
          image: retailpulse-airflow:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: retailpulse-config
            - secretRef:
                name: retailpulse-secrets
          command:
            - bash
            - -lc
            - |
              airflow db upgrade && \
              airflow users create \
                --username admin \
                --firstname Admin \
                --lastname User \
                --role Admin \
                --email admin@example.com \
                --password admin || true
