apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: retailpulse

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.template.yaml
  - persistentvolumeclaim.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - mlflow-deployment.yaml
  - streamlit-deployment.yaml
  - airflow-init-job.yaml
  - airflow-deployment.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - ingress.yaml
