apiVersion: v1
kind: Secret
metadata:
  name: retailpulse-secrets
  namespace: retailpulse
type: Opaque
stringData:
  POSTGRES_USER: airflow
  POSTGRES_PASSWORD: airflow
  POSTGRES_DB: airflow
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
  AIRFLOW__CORE__FERNET_KEY: change-me
